services:
  # Backend API Server
  - type: web
    name: polymarket-server
    env: node
    buildCommand: cd server && npm ci --only=production
    startCommand: cd server && npm start
    envVars:
      - key: ODDS_API_KEY
        value: 650f7c6bc815f7892bcbd9ae68943b6c
      - key: NODE_ENV
        value: production

  # Frontend Next.js App
  - type: web
    name: polymarket-client
    env: node
    region: oregon
    plan: free
    buildCommand: cd web && npm ci && npm run build
    startCommand: cd web && npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://polymarket-server.onrender.com
      - key: NODE_ENV
        value: production
