services:
  # Backend API Server
  - type: web
    name: polymarket-server
    env: node
    buildCommand: cd server && npm ci --only=production
    startCommand: cd server && npm start
    envVars:
      - key: ODDS_API_KEY
        value: 650f7c6bc815f7892bcbd9ae68943b6c
      - key: NODE_ENV
        value: production

  # Frontend Static Site
  - type: web
    name: polymarket-client
    env: static
    buildCommand: cd web && npm ci && npm run build
    staticPublishPath: web/dist
    envVars:
      - key: VITE_API_BASE
        value: https://polymarket-server.onrender.com
